<a href="https://colab.research.google.com/github/Mehtabsingh03/Big-Data-Analysis/blob/main/LAB_eval_Group2_202301035.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np
arr = np.array([10,52,62,16,16,54,453])
print(arr)


sorted_arr = np.sort(arr);
print(sorted_arr)




[ 10  52  62  16  16  54 453]
[ 10  16  16  52  54  62 453]


In [10]:
import numpy as np
arr = np.array([10,52,62,16,16,54,453])
print(arr)

sorted_indices = np.argsort(arr)

print(sorted_indices)

[ 10  52  62  16  16  54 453]
[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]


In [11]:
import numpy as np
arr = np.array([10,52,62,16,16,54,453])
print(arr)
sorted_arr = np.sort(arr);
unique_arr = np.unique(sorted_arr)
print(unique_arr[:4])


[ 10  52  62  16  16  54 453]
[10 16 52 54]


In [12]:
import numpy as np
arr = np.array([10,52,62,16,16,54,453])
sorted_arr = np.sort(arr);
unique_arr = np.unique(sorted_arr)
print(sorted_arr[-5:])

[ 16  52  54  62 453]
